name: CI

on: [push]

jobs:
  test:
    name: Test / OS ${{ matrix.os }} / Node ${{ matrix.node }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['16']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Run tests
        run: |
          npm ci
          npm test
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
          COURIER_API_KEY: ${{ secrets.COURIER_API_KEY }}
          COURIER_TEMPLATE_ID: ${{ secrets.COURIER_TEMPLATE_ID }}

